const excuses = [
   "My dog ate my homework.",
  "I thought today was a holiday.",
  "I was abducted by aliens last night!",
  "My alarm didn’t go off.",
  "Traffic was unbelievable!",
  "I got stuck in an elevator.",
  "I was waiting for the plumber, and he never showed up.",
  "My computer crashed and I lost everything.",
  "I accidentally locked myself out of my house.",
  "I got lost on the way here.",
  "I spilled coffee on my notes.",
  "My car wouldn’t start.",
  "I had a family emergency.",
  "I thought the meeting was next week.",
  "My phone died and I couldn’t find my way.",
  "I was trying to help someone in need.",
  "I had to take care of my sick pet.",
  "I was caught in a rainstorm without an umbrella.",
  "I forgot my laptop at home.",
  "I had a flat tire.",
  "I was in the wrong building.",
  "I mixed up my schedule.",
  "I was doing community service.",
  "I had an unexpected visitor.",
  "I didn’t feel well this morning.",
  "My bus was late.",
  "I thought I was supposed to work from home.",
  "I couldn’t find a parking spot.",
  "I accidentally set my alarm for PM instead of AM.",
  "I had to help my neighbor with a problem.",
  "I lost track of time while watching my favorite show.",
  "I had a sudden headache and needed to rest.",
  "I was stuck in a long line.",
  "I had a prior commitment I forgot about.",
  "I had a power outage and couldn’t get ready.",
  "I was out of town and didn’t have internet.",
  "I had to pick someone up from the airport.",
  "I dropped my phone in the toilet.",
  "I lost my keys and spent ages looking for them.",
  "I ran out of gas on the way.",
  "I got caught up in a conversation.",
  "I had a wardrobe malfunction.",
  "I thought it was a virtual meeting, not in person.",
  "I was trying to fix my Wi-Fi.",
  "I was volunteering and lost track of time.",
  "My child was sick and I had to stay home.",
  "I had an important phone call I couldn’t miss.",
  "I had a flat tire on the way.",
  "I thought I had more time.",
  "I was practicing for a talent show.",
  "I was involved in a minor accident.",
  "I needed to take care of a family matter.",
  "I was too busy binge-watching my favorite series.",
  "My delivery was late and I had to wait for it.",
  "I didn’t hear the alarm.",
  "I was busy preparing a presentation.",
  "I accidentally booked the wrong day.",
  "I was at a doctor’s appointment.",
  "I forgot about a prior engagement.",
  "I had to attend a last-minute meeting.",
  "I got stuck in a traffic jam due to construction.",
  "I had an emergency at home.",
  "I had to attend a funeral.",
  "I had a sudden family obligation.",
  "My pet sitter canceled last minute.",
  "I was caught in a snowstorm.",
  "I was feeling under the weather.",
  "I was at a wedding.",
  "I got a last-minute ticket to a concert.",
  "I had to take care of some paperwork.",
  "I lost my wallet and had to search for it.",
  "I had to help a friend move.",
  "I was waiting for a repairman all day.",
  "I thought I had already completed the task.",
  "I had to attend a seminar.",
  "I lost track of time while cooking.",
  "I was helping my sibling with a project."
  ];
  
  function generateExcuse() {
    const randomIndex = Math.floor(Math.random() * excuses.length);
    document.getElementById("excuse").textContent = excuses[randomIndex];
  }
  